# config with linear model and polynomial features
dataset:
  path: ./data/train.csv
  target_col: raintomorrow
  id_col: row_id
  is_fake: False
  fake_size: 15000
model:
  mode: logreg
transformer:
  mode: linear
split:
  test_size: 0.33
artifacts:
  path: ./data/pipeline.pickle
logging:
  path: ./data/cache.log