name: code checks

on:
  push:
    branches: [ 01 ]
  pull_request:
    branches: [ 01 ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r ./01/requirements.txt
      - name: run flake8
        run: flake8 ./01/source/
      - name: run pylint
        run: pylint ./01/source/
