name: code checks

on:
  push:
    branches: [ homework1 ]
  pull_request:
    branches: [ homework1 ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r ./ml_project/requirements.txt
      - name: go to project directory
        run: cd ./ml_project
      - name: run flake8
        run: flake8 ./source/
      - name: run pylint
        run: pylint ./source/
      - name: run tests
        run: pytest ./source/test.py
